game:
  game_rule: "v1.2"
  max_time: 200
  interaction_model:
    tagging: both_kill
    capture: kill
    prioritize: tagging
  payoff_model:
    model: zero_sum_reward
    constants:
      red_capture: 1.0
      blue_capture: 1.0
      red_killed: 0.5
      blue_killed: 0.5
  

agents:
  red_global:
    speed: 1
    capture_radius: 2
    # sensing_radius: 400
    sensing_radius: 350
    sensors:
    - global_map
    - candidate_flag
    - agent
    - egocentric_flag
    - egocentric_map
  blue_global:
    speed: 1
    tagging_radius: 1
    # sensing_radius: 250 
    sensing_radius: 300
    sensors:
    - global_map
    - custom_team
    - egocentric_agent
    - egocentric_map
    - flag
    - stationary
  red_config: {}
  blue_config: {}

flags:
  real_positions: null
  candidate_positions: null
environment:
  graph_name: null
  blue_stationary_sensor_radius: 450
  blue_static_sensor_positions: null
generator: {}