game:
  game_rule: v1.2
  max_time: 200
  interaction_model:
    tagging: both_kill
    capture: kill
    prioritize: tagging
  payoff_model:
    model: zero_sum_reward
    capture_constant: 1.0
    tagging_constant: 0.5
    detection_constant: 0.1
agents:
  red_global:
    speed: 1
    capture_radius: 2
    sensing_radius: 400
    sensors:
    - global_map
    - candidate_flag
    - agent
    - egocentric_flag
    - egocentric_map
  blue_global:
    speed: 1
    tagging_radius: 1
    sensing_radius: 250
    sensors:
    - global_map
    - custom_team
    - egocentric_agent
    - egocentric_map
    - flag
    - stationary
  red_config:
    red_0:
      start_node_id: 173
    red_1:
      start_node_id: 175
  blue_config:
    blue_0:
      start_node_id: 3
    blue_1:
      start_node_id: 17
    blue_2:
      start_node_id: 4
flags:
  real_positions:
  - 2
  - 4
  candidate_positions: &id001
  - 2
  - 4
  - 6
  - 7
environment:
  graph_name: graph_200_200_a.pkl
  blue_stationary_sensor_radius: 450
  blue_static_sensor_positions: *id001
generator:
  id: 47b07c44d8
  ts: '2025-11-20 11:36:23'
  cafl:
  - 1
  - 4
  - normal_t
  - 2
  - 1
  - 1.0
  reag:
  - 1
  - 2
  - normal_t
  - 10
  - 2
  - 1
  blag:
  - 1
  - 3
  - normal_t
  - 3
  - 1
  - 1
